/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Erlan
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        studregist = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        studcancel = new javax.swing.JButton();
        studLog = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        studUserName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        studUserPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 60)); // NOI18N
        jLabel3.setText("STUDENT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        studregist.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        studregist.setForeground(new java.awt.Color(255, 0, 0));
        studregist.setText("Register");
        getContentPane().add(studregist, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel8.setText("You Don't Have Any Account Yet?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erlan\\Downloads\\student (1).png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erlan\\Downloads\\student (2).png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Garamond", 1, 35)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Log In");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        studcancel.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        studcancel.setText("Cancel");
        studcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studcancelActionPerformed(evt);
            }
        });
        jPanel1.add(studcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 110, 40));

        studLog.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        studLog.setText("Log In");
        studLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studLogActionPerformed(evt);
            }
        });
        jPanel1.add(studLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 110, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel5.setText("UserName:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));
        jPanel1.add(studUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 220, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        studUserPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studUserPassActionPerformed(evt);
            }
        });
        jPanel1.add(studUserPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 550, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erlan\\Desktop\\icons\\rback2.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studcancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studcancelActionPerformed

    private void studLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studLogActionPerformed

    private void studUserPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studUserPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studUserPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton studLog;
    private javax.swing.JTextField studUserName;
    private javax.swing.JTextField studUserPass;
    private javax.swing.JButton studcancel;
    private javax.swing.JLabel studregist;
    // End of variables declaration//GEN-END:variables
}
